# Generated by Django 2.2.4 on 2019-09-03 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20190902_1852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-amount']},
        ),
    ]
